version: '2'

services:

  openresty:
    image: openresty/openresty:alpine
    volumes:
      - ./openresty/conf.d/:/etc/nginx/conf.d/
      - ./openresty/nginx.conf:/usr/local/openresty/nginx/conf/nginx.conf
    ports:
      - "3001:3001"
