version: '2'

services:

  openresty:
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - ./openresty/conf.d/:/usr/local/openresty/nginx/conf.d/
      - ./openresty/lua:/usr/local/openresty/nginx/lua
      - ./openresty/nginx.conf:/usr/local/openresty/nginx/conf/nginx.conf
    ports:
      - "3001:3001"
